### ISSUE TITLE
slechte zin schandalig wouter hoe durf je een fout te maken

### ISSUE THREAD

**Issue by Gastrixx** [wouter-deen/schoolcatalog#1]
"Ik heb de 2e prijs ontvangen mijn short film op het Nationaal Filmfestival voor Scholieren"
moet worden
"Ik heb de 2e prijs ontvangen **met** mijn short film op het Nationaal Filmfestival voor Scholieren" 
oh ja en credits naar het groepje aub dankjewel :)

**Comment by wouter-deen** [comment]
Dat was te lang en daarom had ik dat weggehaald want dat stond er origineel wel maar sure 👍
